file="/path/to/some/file.tar.gz"

echo "${file##*/}"
echo "${file%.*}"
echo "${file%%.*}"
echo "${file#*/}"
echo "${file/path/new}"
echo "${file//\//\\}"
echo "${file:5:10}"
echo "${file:-default}"
echo "${file:+is set}"
echo "${file:?error if unset}"
echo "${#file}"
echo "${file^^}"
echo "${file,,}"
echo "${file~}"
