# ~/.config/hypr/hyprlock.conf

general {
    hide_cursor = true
    ignore_empty_input = true
    immediate_render = true
}

auth {
    pam:enabled = true
    pam:module = hyprlock
}

background {
    monitor =
    color = rgba(111111ff)
}

input-field {
    monitor =
    size = 280, 60
    position = 0, -80
    halign = center
    valign = center

    placeholder_text = Password
    fade_on_empty = false
}

label {
    monitor =
    text = $USER
    position = 0, 20
    halign = center
    valign = center
}
