require("modules.monitors")
require("modules.input")
require("modules.animations")
require("modules.binds")
require("modules.layouts")
require("modules.notifications")

hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd HYPRLAND_INSTANCE_SIGNATURE")
	hl.exec_cmd("hyprshade auto")
end)
