# shellcheck shell=bash
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
export XDG_CONFIG_DIRS="${XDG_CONFIG_DIRS:-/etc/xdg}"
export XDG_DATA_DIRS="${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
export SHELL_ENV_LOADER="${SHELL_ENV_LOADER:-$XDG_CONFIG_HOME/shell/load-env.sh}"
export BASH_ENV="${BASH_ENV:-$XDG_CONFIG_HOME/shell/bash-env.sh}"
