# shellcheck shell=bash
export PIP_CACHE_DIR="${PIP_CACHE_DIR:-$XDG_CACHE_HOME/pip}"
export PYTHONPYCACHEPREFIX="${PYTHONPYCACHEPREFIX:-$XDG_CACHE_HOME/pycache}"
export PYTEST_ADDOPTS="${PYTEST_ADDOPTS:--o cache_dir=$XDG_CACHE_HOME/pytest}"
export RUFF_CACHE_DIR="${RUFF_CACHE_DIR:-$XDG_CACHE_HOME/ruff}"
export UV_CACHE_DIR="${UV_CACHE_DIR:-$XDG_CACHE_HOME/uv}"
export ZSH_CACHE_DIR="${ZSH_CACHE_DIR:-$XDG_CACHE_HOME/zsh}"
mkdir -p "$ZSH_CACHE_DIR"
