package root

goodRootGraph: #RootLifecycleContract & {
	nodes: {
		R: {"@id": "ralph:R", label: "Retrieve", accepted: true, scope: {owns: ["source admissibility"], mayRead: [], mayWrite: ["RetrievalContract"]}, boundaries: {upstream: ["root"], downstream: ["A"], forbidden: ["execute"], authorityMode: "contract"}, inputs: [], outputs: [{id: "retrievalContract", to: "A", kind: "RetrievalContract", acceptedBy: "R.accepted"}], control: {invariants: ["no ambiguity"], rejects: [], acceptance: ["accepted"]}, leaves: []}
		A: {"@id": "ralph:A", label: "Assemble", accepted: true, scope: {owns: ["candidate graph"], mayRead: ["RetrievalContract"], mayWrite: ["TaskGraphContract"]}, boundaries: {upstream: ["R"], downstream: ["L"], forbidden: ["execute"], authorityMode: "contract"}, inputs: [{id: "retrievalContract", from: "R", kind: "RetrievalContract", acceptedRequired: true}], outputs: [{id: "taskGraphContract", to: "L", kind: "TaskGraphContract", acceptedBy: "A.accepted"}], control: {invariants: ["acyclic graph"], rejects: [], acceptance: ["accepted"]}, leaves: []}
		L: {"@id": "ralph:L", label: "Load", accepted: true, scope: {owns: ["bounded context"], mayRead: ["TaskGraphContract"], mayWrite: ["LoadedContext"]}, boundaries: {upstream: ["A"], downstream: ["P"], forbidden: ["execute", "authorize mutation"], authorityMode: "contract"}, inputs: [{id: "taskGraphContract", from: "A", kind: "TaskGraphContract", acceptedRequired: true}], outputs: [{id: "loadedContext", to: "P", kind: "LoadedContext", acceptedBy: "L.accepted"}], control: {invariants: ["bounded loads only"], rejects: [], acceptance: ["accepted"]}, leaves: []}
		P: {"@id": "ralph:P", label: "Promote", accepted: true, scope: {owns: ["mutation validation"], mayRead: ["LoadedContext"], mayWrite: ["PromotionCandidate"]}, boundaries: {upstream: ["L"], downstream: ["H"], forbidden: ["persist", "export"], authorityMode: "evidence"}, inputs: [{id: "loadedContext", from: "L", kind: "LoadedContext", acceptedRequired: true}], outputs: [{id: "promotionCandidate", to: "H", kind: "PromotionCandidate", acceptedBy: "P.accepted"}], control: {invariants: ["observed diff validates"], rejects: [], acceptance: ["accepted"]}, leaves: []}
		H: {"@id": "ralph:H", label: "Harden", accepted: true, scope: {owns: ["final boundary proof"], mayRead: ["PromotionCandidate"], mayWrite: ["AcceptedRunManifest"]}, boundaries: {upstream: ["P"], downstream: [], forbidden: ["execute"], authorityMode: "contract"}, inputs: [{id: "promotionCandidate", from: "P", kind: "PromotionCandidate", acceptedRequired: true}], outputs: [{id: "acceptedRunManifest", to: "cue export", kind: "AcceptedRunManifest", acceptedBy: "H.accepted"}], control: {invariants: ["accepted promotion only"], rejects: [], acceptance: ["accepted"]}, leaves: []}
	}
}
