package root

goodRootGraph: #RootLifecycleContract & {
	nodes: {
		R: {"@id": "ralph:R", label: "Retrieve", accepted: true, scope: {owns: ["source admissibility"], mayRead: [], mayWrite: ["RetrievalContract"]}, boundaries: {upstream: ["root"], downstream: ["A"], forbidden: ["execute"], authorityMode: "contract"}, inputs: [], outputs: [{id: "retrievalContract", to: "A", kind: "RetrievalContract", acceptedBy: "R.accepted"}], control: {invariants: ["no ambiguity"], rejects: [], acceptance: ["accepted"]}, leaves: []}
		A: {"@id": "ralph:A", label: "Assemble", accepted: true, scope: {owns: ["candidate graph"], mayRead: ["RetrievalContract"], mayWrite: ["FlowContract"]}, boundaries: {upstream: ["R"], downstream: ["L"], forbidden: ["execute"], authorityMode: "contract"}, inputs: [{id: "retrievalContract", from: "R", kind: "RetrievalContract", acceptedRequired: true}], outputs: [{id: "flowContract", to: "L", kind: "FlowContract", acceptedBy: "A.accepted"}], control: {invariants: ["acyclic graph"], rejects: [], acceptance: ["accepted"]}, leaves: []}
		L: {"@id": "ralph:L", label: "Legitimize", accepted: true, scope: {owns: ["legitimacy"], mayRead: ["FlowContract"], mayWrite: ["ValidationFacts"]}, boundaries: {upstream: ["A"], downstream: ["P"], forbidden: ["execute"], authorityMode: "contract"}, inputs: [{id: "flowContract", from: "A", kind: "FlowContract", acceptedRequired: true}], outputs: [{id: "validationFacts", to: "P", kind: "ValidationFacts", acceptedBy: "L.accepted"}], control: {invariants: ["no adapter policy"], rejects: [], acceptance: ["accepted"]}, leaves: []}
		P: {"@id": "ralph:P", label: "Perform", accepted: true, scope: {owns: ["run evidence"], mayRead: ["ValidationFacts"], mayWrite: ["RunManifest"], mayExecute: true}, boundaries: {upstream: ["L"], downstream: ["H"], forbidden: ["persist"], authorityMode: "evidence"}, inputs: [{id: "validationFacts", from: "L", kind: "ValidationFacts", acceptedRequired: true}], outputs: [{id: "runManifest", to: "H", kind: "RunManifest", acceptedBy: "P.accepted"}], control: {invariants: ["execute only legitimized tasks"], rejects: [], acceptance: ["accepted"]}, leaves: []}
		H: {"@id": "ralph:H", label: "Harden", accepted: true, scope: {owns: ["durable lifecycle record"], mayRead: ["RunManifest"], mayWrite: ["LifecycleRecord"], mayPersist: true}, boundaries: {upstream: ["P"], downstream: [], forbidden: ["execute"], authorityMode: "contract"}, inputs: [{id: "runManifest", from: "P", kind: "RunManifest", acceptedRequired: true}], outputs: [{id: "lifecycleRecord", to: "durable-state", kind: "LifecycleRecord", acceptedBy: "H.accepted"}], control: {invariants: ["accepted run only"], rejects: [], acceptance: ["accepted"]}, leaves: []}
	}
}
