shell = "bash -lc '{}'"
default-scheme = "base16-tokyo-night-storm"

hooks = ["~/.local/bin/tinty-broot-hook"]

[[items]]
name = "tinted-shell"
path = "https://github.com/tinted-theming/tinted-shell"
themes-dir = "scripts"
hook = '''
. "$TINTY_THEME_FILE_PATH"
'''
supported-systems = ["base16", "base24"]

[[items]]
name = "tinted-kitty"
path = "https://github.com/tinted-theming/tinted-kitty"
themes-dir = "colors"
hook = '''
mkdir -p "$HOME/.local/state/kitty"
cp -f "$TINTY_THEME_FILE_PATH" "$HOME/.local/state/kitty/current-theme.conf"
if command -v kitty >/dev/null 2>&1; then
  kitty @ set-colors -a -c "$HOME/.local/state/kitty/current-theme.conf" >/dev/null 2>&1 || true
fi
'''
supported-systems = ["base16", "base24"]

[[items]]
name = "tinted-vim"
path = "https://github.com/tinted-theming/tinted-vim"
themes-dir = "colors"
hook = '''
mkdir -p "$HOME/.config/nvim/colors"
cp -f "$TINTY_THEME_FILE_PATH" "$HOME/.config/nvim/colors/tinted.vim"
'''
supported-systems = ["base16", "base24"]

[[items]]
name = "tinted-yazi"
path = "https://github.com/tinted-theming/tinted-yazi"
themes-dir = "flavors"
hook = '''
mkdir -p "$HOME/.config/yazi/flavors/tinted-scheme.yazi"
cp -f "$TINTY_THEME_FILE_PATH" "$HOME/.config/yazi/flavors/tinted-scheme.yazi/flavor.toml"
'''
supported-systems = ["base16"]

[[items]]
name = "tinted-delta"
path = "https://github.com/tinted-theming/tinted-delta"
themes-dir = "configs"
supported-systems = ["base16", "base24"]

[[items]]
name = "base16-gtk-flatcolor-gtk2"
path = "https://github.com/tinted-theming/base16-gtk-flatcolor"
themes-dir = "gtk-2"
theme-file-extension = "-gtkrc"
hook = '''
mkdir -p "$HOME/.themes/FlatColor"
cp -f "$TINTY_THEME_FILE_PATH" "$HOME/.themes/FlatColor/colors2"
'''
supported-systems = ["base16"]

[[items]]
name = "base16-gtk-flatcolor-gtk3"
path = "https://github.com/tinted-theming/base16-gtk-flatcolor"
themes-dir = "gtk-3"
theme-file-extension = "-gtk.css"
hook = '''
mkdir -p "$HOME/.themes/FlatColor"
cp -f "$TINTY_THEME_FILE_PATH" "$HOME/.themes/FlatColor/colors3"
'''
supported-systems = ["base16"]
