[mgr]
prepend_keymap = [
  { on = "<A-y>", run = "plugin copy-file-contents", desc = "Copy contents of file" },
  { on = "<Enter>", run = "open", desc = "Open selected files" },
  { on = [ "g", "." ], run = "hidden toggle", desc = "Toggle hidden files" },
  { on = [ "g", "i" ], run = "plugin lazygit", desc = "Launch lazygit" },
  { on = ["C"], run = "plugin ouch", desc = "Compress with ouch" },
]
