// Code-generated by ChatGPT from skills.zip on 2026-05-19.
// Root skill reference manifest: canonical skill registry + upstream reference source candidates.
package agent_sdk

skills: {
	"agent-sdk": {
		id: "agent-sdk"
		path: "skills/agent-sdk"
		title: "agent-sdk"
		purpose: "Use agent-sdk to initialize, generate, check, and project managed agent runtimes and repo projects."
		upstream: {
			kind: "local"
			source: "$AGENT_SDK_SOURCE"
		}
		references: {
			upstream_include: []
			projected_include: [
				"SKILL.md",
				"skill.cue",
				"references/INDEX.md",
				"references/provenance.json",
			]
		}
		adapters: {
			codex: {
				enabled: true
				output: "skills/agent-sdk"
			}
		}
	}
	argc: {
		id: "argc"
		path: "skills/argc"
		title: "argc"
		purpose: "Argc annotation and argv-context guidance inside Bash source scripts."
		upstream: {
			kind: "github"
			repo: "sigoden/argc"
			ref: "main"
			url: "https://github.com/sigoden/argc"
		}
		references: {
			upstream_include: [
				"README.md",
				"docs",
				"examples",
			]
			projected_include: [
				"SKILL.md",
				"AGENTS.md",
				"references/INDEX.md",
				"references/provenance.json",
				"references/docs",
				"references/patterns",
			]
		}
		adapters: {
			codex: {
				enabled: true
				output: "skills/argc"
			}
		}
	}
	"bash-ast": {
		id: "bash-ast"
		path: "skills/bash-ast"
		title: "bash-ast"
		purpose: "Optional Bash parse and semantic evidence using bash-ast or ast-bash."
		upstream: {
			kind: "github"
			repo: "cv/bash-ast"
			ref: "main"
			url: "https://github.com/cv/bash-ast"
		}
		references: {
			upstream_include: [
				"README.md",
				"HOMEBREW.md",
				"tests",
			]
			projected_include: [
				"SKILL.md",
				"AGENTS.md",
				"references/INDEX.md",
				"references/provenance.json",
				"references/docs",
				"references/patterns",
				"references/fixtures",
			]
		}
		adapters: {
			codex: {
				enabled: true
				output: "skills/bash-ast"
			}
		}
	}
	bashly: {
		id: "bashly"
		path: "skills/bashly"
		title: "bashly"
		purpose: "Bashly source-edit workflow for Bashly config, source scripts, generated artifact boundaries, and CLI behavior reasoning."
		upstream: {
			kind: "github"
			repo: "bashly-framework/bashly"
			ref: "master"
			url: "https://github.com/bashly-framework/bashly"
			docs_url: "https://bashly.dev/"
		}
		references: {
			upstream_include: [
				"README.md",
				"docs",
				"examples",
			]
			projected_include: [
				"SKILL.md",
				"AGENTS.md",
				"references/INDEX.md",
				"references/provenance.json",
				"references/docs",
				"references/patterns",
			]
		}
		adapters: {
			codex: {
				enabled: true
				output: "skills/bashly"
			}
		}
	}
	"bats-core": {
		id: "bats-core"
		path: "skills/bats-core"
		title: "bats-core"
		purpose: "Bats black-box CLI behavior tests for shell CLIs and Bashly-generated command behavior."
		upstream: {
			kind: "github"
			repo: "bats-core/bats-core"
			ref: "master"
			url: "https://github.com/bats-core/bats-core"
			docs_url: "https://bats-core.readthedocs.io/"
		}
		references: {
			upstream_include: [
				"README.md",
				"docs",
				"man",
			]
			projected_include: [
				"SKILL.md",
				"AGENTS.md",
				"references/INDEX.md",
				"references/provenance.json",
				"references/docs",
				"references/patterns",
				"references/fixtures",
			]
		}
		adapters: {
			codex: {
				enabled: true
				output: "skills/bats-core"
			}
		}
	}
	cue: {
		id: "cue"
		path: "skills/cue"
		title: "CUE"
		purpose: "Use CUE as schema, validation, graph, and projection authority."
		upstream: {
			kind: "github"
			repo: "cue-lang/cue"
			ref: "master"
			url: "https://github.com/cue-lang/cue"
			docs_repos: [
				{
					repo: "cue-lang/cuelang.org"
					ref: "master"
					url: "https://github.com/cue-lang/cuelang.org"
				},
			]
		}
		references: {
			upstream_include: [
				"doc/ref/spec.md",
				"doc/ref/impl.md",
				"doc/cmd/cue.md",
				"doc/context/language-features.md",
				"doc/tutorial/basics/README.md",
			]
			projected_include: [
				"SKILL.md",
				"references/INDEX.md",
				"references/provenance.json",
				"references/docs",
				"references/patterns",
				"references/fixtures",
			]
		}
		adapters: {
			codex: {
				enabled: true
				output: "skills/cue"
			}
		}
	}
	"repo-search": {
		id: "repo-search"
		path: "skills/repo-search"
		title: "repo-search"
		purpose: "Bounded repository search before broad source inspection."
		upstream: {
			kind: "github"
			repo: "burntsushi/ripgrep"
			ref: "master"
			url: "https://github.com/BurntSushi/ripgrep"
		}
		references: {
			upstream_include: [
				"README.md",
				"GUIDE.md",
				"FAQ.md",
				"doc/rg.1.md",
			]
			projected_include: [
				"SKILL.md",
				"repo-rg",
				"references/INDEX.md",
				"references/provenance.json",
			]
		}
		adapters: {
			codex: {
				enabled: true
				output: "skills/repo-search"
			}
		}
	}
	sem: {
		id: "sem"
		path: "skills/sem"
		title: "sem"
		purpose: "Deterministic semantic repository intelligence for diffs, entities, context, impact, blame, and history."
		upstream: {
			kind: "github"
			repo: "Ataraxy-Labs/sem"
			ref: "main"
			url: "https://github.com/Ataraxy-Labs/sem"
			docs_url: "https://ataraxy-labs.github.io/sem/"
		}
		references: {
			upstream_include: [
				"README.md",
				"docs/llms.txt",
				"docs/agents.html",
				"docs/details.html",
			]
			projected_include: [
				"SKILL.md",
				"references/INDEX.md",
				"references/provenance.json",
				"references/docs",
				"references/patterns",
				"references/fixtures",
			]
		}
		adapters: {
			codex: {
				enabled: true
				output: "skills/sem"
			}
		}
	}
	"shell-validation": {
		id: "shell-validation"
		path: "skills/shell-validation"
		title: "shell-validation"
		purpose: "Local shell validation: shellharden, shfmt, shellcheck, and pre-commit lint/format gates."
		upstream: {
			kind: "composite"
			repos: [
				{
					id: "shellcheck"
					repo: "koalaman/shellcheck"
					ref: "master"
					url: "https://github.com/koalaman/shellcheck"
					include: [
						"README.md",
						"wiki",
					]
				},
				{
					id: "shfmt"
					repo: "mvdan/sh"
					ref: "master"
					url: "https://github.com/mvdan/sh"
					include: [
						"README.md",
						"cmd/shfmt",
						"cmd/shfmt/shfmt.1.scd",
					]
				},
			]
		}
		references: {
			upstream_include: [
				"shellcheck/README.md",
				"shellcheck/wiki",
				"shfmt/README.md",
				"shfmt/cmd/shfmt",
				"shfmt/cmd/shfmt/shfmt.1.scd",
			]
			projected_include: [
				"SKILL.md",
				"AGENTS.md",
				"references/INDEX.md",
				"references/provenance.json",
				"references/docs",
				"references/patterns",
			]
		}
		adapters: {
			codex: {
				enabled: true
				output: "skills/shell-validation"
			}
		}
	}
	shellspec: {
		id: "shellspec"
		path: "skills/shellspec"
		title: "shellspec"
		purpose: "ShellSpec unit/component tests for sourceable shell functions, helpers, mocks, and parameterized examples."
		upstream: {
			kind: "github"
			repo: "shellspec/shellspec"
			ref: "master"
			url: "https://github.com/shellspec/shellspec"
			docs_url: "https://shellspec.info/"
		}
		references: {
			upstream_include: [
				"README.md",
				"docs",
				"examples",
			]
			projected_include: [
				"SKILL.md",
				"AGENTS.md",
				"references/INDEX.md",
				"references/provenance.json",
				"references/docs",
				"references/patterns",
				"references/fixtures",
			]
		}
		adapters: {
			codex: {
				enabled: true
				output: "skills/shellspec"
			}
		}
	}
	"tree-sitter": {
		id: "tree-sitter"
		path: "skills/tree-sitter"
		title: "tree-sitter"
		purpose: "Optional structural inspection evidence for source edits using tree-sitter-cli."
		upstream: {
			kind: "github"
			repo: "tree-sitter/tree-sitter"
			ref: "master"
			url: "https://github.com/tree-sitter/tree-sitter"
			docs_url: "https://tree-sitter.github.io/tree-sitter/"
		}
		references: {
			upstream_include: [
				"README.md",
				"docs",
				"cli",
			]
			projected_include: [
				"SKILL.md",
				"AGENTS.md",
				"references/INDEX.md",
				"references/provenance.json",
				"references/docs",
				"references/patterns",
				"references/fixtures",
			]
		}
		adapters: {
			codex: {
				enabled: true
				output: "skills/tree-sitter"
			}
		}
	}
}

system_skills: {
	excluded_from_runtime_projection_v0: true
	reason: "platform/system skills are not canonical agent-sdk user skills in v0"
	paths: [
		"skills/.system/imagegen",
		"skills/.system/openai-docs",
		"skills/.system/plugin-creator",
		"skills/.system/skill-creator",
		"skills/.system/skill-installer",
	]
}
