XDG_CACHE_HOME=${XDG_CACHE_HOME:-${HOME}/.cache}
XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-${HOME}/.config}
XDG_DATA_HOME=${XDG_DATA_HOME:-${HOME}/.local/share}
XDG_STATE_HOME=${XDG_STATE_HOME:-${HOME}/.local/state}

XDG_CONFIG_DIRS=${XDG_CONFIG_DIRS:-/etc/xdg}
XDG_DATA_DIRS=${XDG_DATA_DIRS:-/usr/local/share:/usr/share}

DOTS_SOURCE_DIR=${DOTS_SOURCE_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/chezmoi}

PIP_CACHE_DIR=${PIP_CACHE_DIR:-${XDG_CACHE_HOME}/pip}
PYTHONPYCACHEPREFIX=${PYTHONPYCACHEPREFIX:-${XDG_CACHE_HOME}/pycache}
RUFF_CACHE_DIR=${RUFF_CACHE_DIR:-${XDG_CACHE_HOME}/ruff}
UV_CACHE_DIR=${UV_CACHE_DIR:-${XDG_CACHE_HOME}/uv}

ZSH_CACHE_DIR=${ZSH_CACHE_DIR:-${XDG_CACHE_HOME}/zsh}

XDG_DATA_BIN=${XDG_DATA_BIN:-${HOME}/.local/bin}
TOOL_PATH_HOME=${TOOL_PATH_HOME:-${XDG_DATA_HOME}/path}

CARGO_HOME=${CARGO_HOME:-${XDG_DATA_HOME}/cargo}
RUSTUP_HOME=${RUSTUP_HOME:-${XDG_DATA_HOME}/rustup}

GO_HOME=${GO_HOME:-${XDG_DATA_HOME}/go}
GOPATH=${GOPATH:-${GO_HOME}}
GOBIN=${GOBIN:-${GOPATH}/bin}
GOMODCACHE=${GOMODCACHE:-${GOPATH}/pkg/mod}
GOCACHE=${GOCACHE:-${XDG_CACHE_HOME}/go-build}
GOTOOLCHAIN=${GOTOOLCHAIN:-auto}
GOPRIVATE=${GOPRIVATE:-github.com/fatb4f/*}
GONOSUMDB=${GONOSUMDB:-github.com/fatb4f/*}
GOPROXY=${GOPROXY:-https://proxy.golang.org,direct}

npm_config_userconfig=${npm_config_userconfig:-${XDG_CONFIG_HOME}/npm/npmrc}
npm_config_cache=${npm_config_cache:-${XDG_CACHE_HOME}/npm}
npm_config_prefix=${npm_config_prefix:-${XDG_DATA_HOME}/npm}

KITTY_CONFIG_DIRECTORY=${KITTY_CONFIG_DIRECTORY:-${XDG_CONFIG_HOME}/kitty}
KITTY_CACHE_DIRECTORY=${KITTY_CACHE_DIRECTORY:-${XDG_CACHE_HOME}/kitty}

SHELL=${SHELL:-/usr/sbin/zsh}
TERMINAL=${TERMINAL:-wezterm}
EDITOR=${EDITOR:-nvim}
VISUAL=${VISUAL:-nvim}

ANDROID_USER_HOME=${ANDROID_USER_HOME:-${XDG_DATA_HOME}/android}
PASSWORD_STORE_DIR=${PASSWORD_STORE_DIR:-${XDG_DATA_HOME}/pass}
LESSHISTFILE=${LESSHISTFILE:-${XDG_STATE_HOME}/lesshst}
GNUPGHOME=${GNUPGHOME:-${XDG_DATA_HOME}/gnupg}

CODEX_HOME=${CODEX_HOME:-${XDG_DATA_HOME}/codex}
CODEX_BIN=${CODEX_BIN:-${CODEX_HOME}/bin}
CODEX_STATE=${CODEX_STATE:-${XDG_STATE_HOME}/codex}
CODEX_CACHE=${CODEX_CACHE:-${XDG_CACHE_HOME}/codex}
CODEX_SQLITE_HOME=${CODEX_SQLITE_HOME:-${CODEX_STATE}/sqlite}

QT_QPA_PLATFORMTHEME=qt6ct
